In [1]:
import pandas

In [2]:
ds = pandas.read_csv("50_Startups.csv")

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [4]:
X = ds[["R&D Spend", "Administration", "Marketing Spend"]]

In [6]:
X.shape

(50, 3)

In [7]:
state = ds["State"]

In [8]:
y = ds["Profit"]

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()

In [11]:
state_le = le.fit_transform(state)

In [12]:
state_le

array([2, 0, 1, 2, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 2, 0, 2, 1, 2, 0, 2,
       1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 0, 1, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2,
       0, 2, 1, 0, 2, 0])

In [18]:
state_lef = state_le.reshape(50,1)

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
ohe = OneHotEncoder()

In [24]:
state_ohe =ohe.fit_transform(state_lef)

In [25]:
state_ohe

<50x3 sparse matrix of type '<class 'numpy.float64'>'
	with 50 stored elements in Compressed Sparse Row format>

In [27]:
state_ohe_final = state_ohe.toarray()

In [28]:
state_final_trap = state_ohe_final[:, 0:2]

In [31]:
import numpy

In [33]:
x_final = numpy.hstack((X, state_final_trap))

In [34]:
from sklearn.linear_model import LinearRegression

In [35]:
model = LinearRegression()

In [36]:
model.fit(x_final, y)

LinearRegression()

In [37]:
model.coef_

array([ 8.06023114e-01, -2.70043196e-02,  2.69798610e-02,  4.18870191e+01,
        2.40675812e+02])

In [39]:
model.predict()

TypeError: predict() missing 1 required positional argument: 'X'

In [42]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
dtypes: float64(3)
memory usage: 1.3 KB


In [43]:
import pandas
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy
ds = pandas.read_csv('50_Startups.csv')
X = ds[ ["R&D Spend", "Administration", "Marketing Spend"] ]
y = ds["Profit"]
state = ds["State"]
le = LabelEncoder()
state_le = le.fit_transform(state)
state_le_2d = state_le.reshape(50,1)
ohe = OneHotEncoder()
state_ohe =ohe.fit_transform(state_le_2d)
state_ohe_final = state_ohe.toarray()
state_final_trap = state_ohe_final[:, 0:2]
x_final = numpy.hstack((X, state_final_trap))
model = LinearRegression()
model.fit(x_final, y)
model.coef_

array([ 8.06023114e-01, -2.70043196e-02,  2.69798610e-02,  4.18870191e+01,
        2.40675812e+02])